"""empty message

Revision ID: 814f6aa1bba5
Revises: cb29908c1dd5
Create Date: 2023-08-08 15:01:02.042160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '814f6aa1bba5'
down_revision = 'cb29908c1dd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=1500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('sys_c0010655')

    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id', name='sys_c0010654')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('sys_c0010655', ['username'], unique=False)

    op.drop_table('news')
    # ### end Alembic commands ###
